"""Air-gapped markdown export for full index serialization."""

import io
import sys
import tarfile
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from glma.db.ladybug_store import LadybugStore
from glma.models import Chunk, ChunkType, ExportConfig
from glma.summaries import generate_rule_summary

logger = logging.getLogger(__name__)



def _format_export_file(
    file_path: str,
    file_record: Optional[object],
    chunks: list[Chunk],
    relationships: list[dict],
    config: ExportConfig,
    file_summary: str = "",
) -> str:
    """Generate enriched markdown for a single file in the export.

    Includes metadata header, file summary, chunks, and relationships.

    Args:
        file_path: Relative file path from repo root.
        file_record: FileRecord object (or None if metadata unavailable).
        chunks: All chunks for the file.
        relationships: All relationships for the file.
        config: Export configuration.
        file_summary: Pre-computed file-level summary (AI or rule-based).

    Returns:
        Complete markdown string for this file.
    """
    lines: list[str] = []

    # Metadata header (YAML frontmatter)
    lines.append("---")
    lines.append(f"file_path: {file_path}")
    if file_record:
        lang_val = file_record.language.value if hasattr(file_record.language, 'value') else str(file_record.language)
        lines.append(f"language: {lang_val}")
        lines.append(f"last_indexed: {file_record.last_indexed}")
        lines.append(f"chunk_count: {file_record.chunk_count}")
        lines.append(f"content_hash: {file_record.content_hash}")
    lines.append("---")
    lines.append("")

    # File heading
    lines.append(f"# {file_path}")
    lines.append("")

    # Summary section
    lines.append("## Summary")
    lines.append("")
    ai_chunks = [c for c in chunks if c.summary]

    if ai_chunks:
        # Use AI summaries as the primary file summary
        for c in ai_chunks:
            lines.append(f"- **{c.name}**: {c.summary}")
    else:
        # Fall back to rule-based summary
        lines.append(file_summary or generate_rule_summary(file_path, chunks, relationships))

    lines.append("")

    # Key Exports table
    lines.append("## Key Exports")
    lines.append("")
    lines.append("| Name | Type | Line Range | Description |")
    lines.append("| ---- | ---- | ---------- | ----------- |")

    exports = [c for c in chunks if c.parent_id is None]
    if exports:
        for chunk in exports:
            desc = ""
            if chunk.attached_comments:
                desc = chunk.attached_comments[0].strip()[:80]
            lines.append(f"| {chunk.name} | {chunk.chunk_type.value} | L{chunk.start_line}-L{chunk.end_line} | {desc} |")
    else:
        lines.append("| *(no exports found)* | | | |")
    lines.append("")

    # Chunks section
    lines.append("## Chunks")
    lines.append("")

    for chunk in chunks:
        lines.append(f"### {chunk.name} ({chunk.chunk_type.value}, L{chunk.start_line}-L{chunk.end_line})")
        lines.append("")

        # Chunk summary (from DB — generated by `glma index --summarize`)
        if chunk.summary:
            lines.append(f"> *Summary: {chunk.summary}*")
            lines.append("")

        if config.include_code:
            # Language hint for code block
            lang_hint = ""
            if file_path.endswith(".py"):
                lang_hint = "python"
            elif file_path.endswith(".c") or file_path.endswith(".h"):
                lang_hint = "c"
            lines.append(f"```{lang_hint}")
            lines.append(chunk.content)
            lines.append("```")
        else:
            if chunk.summary:
                # Summary already shown above, code omitted is implicit
                pass
            else:
                lines.append(f"*(Code omitted. Signature: L{chunk.start_line}-L{chunk.end_line})*")

        # Inline relationships
        chunk_rels = [r for r in relationships if r.get("source_id") == chunk.id]
        if chunk_rels:
            parts = []
            for r in chunk_rels:
                target = r.get("target_name", "?")
                if r.get("source_id") == r.get("target_id"):
                    target = f"? ({r.get('target_name', 'unknown')})"
                conf = r.get("confidence", "INFERRED")
                parts.append(f"{target} ({conf})")
            if parts:
                lines.append(f"> **Calls:** {', '.join(parts)}")

        lines.append("")

    # Relationships section
    if relationships:
        lines.append("## Relationships")
        lines.append("")

        # Group by type
        by_type: dict[str, list[dict]] = {}
        for r in relationships:
            rt = r.get("rel_type", "unknown")
            by_type.setdefault(rt, []).append(r)

        chunk_ids = {c.id for c in chunks}

        # Outgoing calls
        out_calls = [r for r in by_type.get("calls", []) if r.get("source_id") in chunk_ids]
        if out_calls:
            lines.append("### Outgoing Calls")
            lines.append("")
            lines.append("| From | To | Confidence | Line |")
            lines.append("| ---- | -- | ---------- | ---- |")
            for r in out_calls:
                from_name = r.get("source_name", "?")
                target = r.get("target_name_resolved", r.get("target_name", "?"))
                if r.get("source_id") == r.get("target_id"):
                    target = f"? ({r.get('target_name', 'unknown')})"
                lines.append(f"| {from_name} | {target} | {r.get('confidence', '')} | L{r.get('source_line', '')} |")
            lines.append("")

        # Incoming calls
        incoming_calls = [r for r in relationships if r.get("rel_type") == "calls" and r.get("direction") == "incoming"]
        if incoming_calls:
            lines.append("### Incoming Calls")
            lines.append("")
            lines.append("| From | To | Confidence |")
            lines.append("| ---- | -- | ---------- |")
            for r in incoming_calls:
                lines.append(f"| {r.get('source_name', '?')} | {r.get('target_name', '?')} | {r.get('confidence', '')} |")
            lines.append("")

        # Imports
        imports = [r for r in by_type.get("imports", []) if r.get("source_id") in chunk_ids]
        if imports:
            lines.append("### Imports")
            lines.append("")
            lines.append("| Import | Confidence |")
            lines.append("| ------ | ---------- |")
            for r in imports:
                lines.append(f"| {r.get('target_name', '')} | {r.get('confidence', '')} |")
            lines.append("")

        # Includes (C)
        includes = [r for r in by_type.get("includes", []) if r.get("source_id") in chunk_ids]
        if includes:
            lines.append("### Includes")
            lines.append("")
            lines.append("| Include | Confidence |")
            lines.append("| ------- | ---------- |")
            for r in includes:
                lines.append(f"| {r.get('target_name', '')} | {r.get('confidence', '')} |")
            lines.append("")

        # Inherits
        inherits = [r for r in by_type.get("inherits", []) if r.get("source_id") in chunk_ids]
        if inherits:
            lines.append("### Inherits")
            lines.append("")
            lines.append("| Class | Base | Confidence |")
            lines.append("| ----- | ---- | ---------- |")
            for r in inherits:
                from_name = r.get("source_name", "?")
                target = r.get("target_name_resolved", r.get("target_name", "?"))
                lines.append(f"| {from_name} | {target} | {r.get('confidence', '')} |")
            lines.append("")

    return "\n".join(lines)


def _format_rel_path(file_path: str) -> str:
    """Convert file path to export-relative path for links.

    Example: src/auth/login.py -> src/auth/login.py.md
    """
    return file_path + ".md"


def generate_index_md(
    indexed_files: dict,
    file_data: dict[str, dict],
) -> str:
    """Generate the root INDEX.md with file listing and statistics.

    Args:
        indexed_files: Dict of {path: content_hash} from store.get_indexed_files().
        file_data: Dict of {path: {"chunks": [...], "record": FileRecord, "summary": str}}.

    Returns:
        Complete INDEX.md markdown string.
    """
    lines: list[str] = []

    lines.append("# Codebase Index")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).isoformat()}")
    lines.append(f"**Total Files:** {len(indexed_files)}")

    total_chunks = sum(len(d.get("chunks", [])) for d in file_data.values())
    lines.append(f"**Total Chunks:** {total_chunks}")
    lines.append("")

    # File table
    lines.append("## Files")
    lines.append("")
    lines.append("| File | Language | Chunks | Summary |")
    lines.append("| ---- | -------- | ------ | ------- |")

    for path in sorted(indexed_files.keys()):
        data = file_data.get(path, {})
        record = data.get("record")
        chunks = data.get("chunks", [])
        summary = data.get("summary", "")

        lang = record.language.value if record and hasattr(record, "language") else "?"
        chunk_count = len(chunks)
        rel_link = _format_rel_path(path)

        # Truncate summary for table display
        short_summary = summary[:60] + "..." if len(summary) > 60 else summary

        lines.append(f"| [{path}]({rel_link}) | {lang} | {chunk_count} | {short_summary} |")

    lines.append("")

    # Statistics
    lines.append("## Statistics")
    lines.append("")

    all_chunks = []
    for d in file_data.values():
        all_chunks.extend(d.get("chunks", []))

    func_count = sum(1 for c in all_chunks if c.chunk_type == ChunkType.FUNCTION)
    class_count = sum(1 for c in all_chunks if c.chunk_type == ChunkType.CLASS)
    method_count = sum(1 for c in all_chunks if c.chunk_type == ChunkType.METHOD)

    lines.append(f"- Total functions: {func_count}")
    lines.append(f"- Total classes: {class_count}")
    lines.append(f"- Total methods: {method_count}")
    lines.append(f"- Total files: {len(indexed_files)}")
    lines.append("")

    return "\n".join(lines)


def generate_relationships_md(
    file_data: dict[str, dict],
) -> str:
    """Generate the root RELATIONSHIPS.md with full cross-file dependency graph.

    Args:
        file_data: Dict of {path: {"chunks": [...], "relationships": [...]}}.

    Returns:
        Complete RELATIONSHIPS.md markdown string.
    """
    lines: list[str] = []

    lines.append("# Cross-File Relationships")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).isoformat()}")
    lines.append("")

    # Collect all cross-file relationships
    cross_file_rels: list[dict] = []
    for path, data in file_data.items():
        rels = data.get("relationships", [])
        chunks = data.get("chunks", [])
        chunk_ids = {c.id for c in chunks}

        for rel in rels:
            source_id = rel.get("source_id", "")
            target_id = rel.get("target_id", "")

            # Skip self-referential (unresolved) edges for cross-file display
            if source_id == target_id:
                continue
            # We only want relationships where source and target are in different files
            if source_id in chunk_ids and target_id not in chunk_ids:
                cross_file_rels.append({
                    "source_file": path,
                    "source_name": rel.get("source_name", "?"),
                    "rel_type": rel.get("rel_type", "?"),
                    "target_name": rel.get("target_name_resolved", rel.get("target_name", "?")),
                })

    total = len(cross_file_rels)
    lines.append(f"**Total Cross-File Relationships:** {total}")
    lines.append("")

    if cross_file_rels:
        lines.append("## Dependency Graph")
        lines.append("")
        lines.append("| Source File | Source Chunk | Type | Target |")
        lines.append("| ----------- | ------------ | ---- | ------ |")

        for rel in sorted(cross_file_rels, key=lambda r: (r["source_file"], r["rel_type"])):
            src_link = f"[{rel['source_file']}]({_format_rel_path(rel['source_file'])})"
            lines.append(f"| {src_link} | {rel['source_name']} | {rel['rel_type']} | {rel['target_name']} |")

        lines.append("")

    # Per-file dependency summary
    lines.append("## File Dependencies")
    lines.append("")

    for path in sorted(file_data.keys()):
        rels = file_data[path].get("relationships", [])
        chunks = file_data[path].get("chunks", [])
        chunk_ids = {c.id for c in chunks}

        imported_by: set[str] = set()
        imports_from: set[str] = set()
        called_by: set[str] = set()
        calls_to: set[str] = set()

        for rel in rels:
            if rel.get("direction") == "incoming":
                src_id = rel.get("source_id", "")
                src_file = src_id.split("::")[0] if "::" in src_id else ""
                if src_file and src_file != path:
                    if rel.get("rel_type") == "imports":
                        imported_by.add(src_file)
                    elif rel.get("rel_type") == "calls":
                        called_by.add(src_file)
            else:
                target_id = rel.get("target_id", "")
                target_file = target_id.split("::")[0] if "::" in target_id else ""
                if target_file and target_file != path and target_id not in chunk_ids:
                    if rel.get("rel_type") == "imports":
                        imports_from.add(target_file)
                    elif rel.get("rel_type") == "calls":
                        calls_to.add(target_file)

        if imported_by or imports_from or called_by or calls_to:
            lines.append(f"### {path}")
            lines.append("")
            if imports_from:
                links = ", ".join(f"[{f}]({_format_rel_path(f)})" for f in sorted(imports_from))
                lines.append(f"**Imports from:** {links}")
            if imported_by:
                links = ", ".join(f"[{f}]({_format_rel_path(f)})" for f in sorted(imported_by))
                lines.append(f"**Imported by:** {links}")
            if calls_to:
                links = ", ".join(f"[{f}]({_format_rel_path(f)})" for f in sorted(calls_to))
                lines.append(f"**Calls:** {links}")
            if called_by:
                links = ", ".join(f"[{f}]({_format_rel_path(f)})" for f in sorted(called_by))
                lines.append(f"**Called by:** {links}")
            lines.append("")

    return "\n".join(lines)


def _get_module_name(file_path: str) -> str:
    """Extract module name from file path.

    Files in subdirectories get the directory name as their module.
    Root-level files get their filename stem as the module name.

    Args:
        file_path: Relative file path (e.g., 'src/glma/db/store.py').

    Returns:
        Module name string.
    """
    parts = Path(file_path).parts
    if len(parts) >= 2:
        # e.g., db/store.py → db, src/glma/db/store.py → db
        # Use the directory just before the filename
        return parts[-2]
    else:
        # e.g., cli.py → cli (root-level file)
        return Path(file_path).stem


def _module_from_import_name(import_name: str, file_data: dict[str, dict]) -> Optional[str]:
    """Resolve an import name (e.g., 'glma.export') to a module name using file_data.

    Tries to match the import name against file paths in file_data.
    Falls back to extracting the last meaningful segment from the import path.

    Args:
        import_name: Dotted import path (e.g., 'glma.db.ladybug_store').
        file_data: Dict of {path: {...}} for file path matching.

    Returns:
        Module name string or None if unresolvable.
    """
    if not import_name:
        return None

    # Try direct match: find a file whose stem matches the last segment of the import
    parts = import_name.split(".")
    if len(parts) >= 2:
        # e.g., glma.export → look for export.py or export/ directory
        last_part = parts[-1]
        for fp in file_data:
            p = Path(fp)
            if p.stem == last_part or p.parts[-2] if len(p.parts) >= 2 else "" == last_part:
                return _get_module_name(fp)

    # Fallback: use the last segment as a heuristic module name
    # e.g., 'glma.models' → 'models', 'glma.db.ladybug_store' → 'ladybug_store' → 'db'
    for fp in file_data:
        stem = Path(fp).stem
        if stem == parts[-1]:
            return _get_module_name(fp)

    return None


def _group_by_module(file_data: dict[str, dict]) -> dict[str, list[str]]:
    """Group file paths by their module name.

    Args:
        file_data: Dict of {path: {record, chunks, relationships, summary}}.

    Returns:
        Dict of {module_name: [file_paths]}, sorted by module name.
    """
    modules: dict[str, list[str]] = {}
    for file_path in file_data:
        module = _get_module_name(file_path)
        modules.setdefault(module, []).append(file_path)
    # Sort file paths within each module
    for mod in modules:
        modules[mod].sort()
    return dict(sorted(modules.items()))


def _detect_entry_points(file_data: dict[str, dict]) -> list[dict]:
    """Detect entry points via convention checks and fan-in analysis.

    Convention checks: __main__.py, cli.py, main.py filenames, and
    ``if __name__ == "__main__"`` in chunk content.
    Fan-in analysis: files with zero incoming imports and outgoing
    relationships are likely entry points.

    Args:
        file_data: Dict of {path: {record, chunks, relationships, summary}}.

    Returns:
        List of dicts with keys: path, method, chunk_names.
    """
    entry_points: list[dict] = []
    convention_files: set[str] = set()

    # Convention detection
    for file_path, data in file_data.items():
        stem = Path(file_path).stem
        if stem in ("__main__", "cli", "main"):
            convention_files.add(file_path)
            chunks = data.get("chunks", [])
            entry_points.append({
                "path": file_path,
                "method": "detected entry point",
                "chunk_names": [c.name for c in chunks if c.parent_id is None],
            })
        else:
            # Check chunk content for __name__ == "__main__"
            for chunk in data.get("chunks", []):
                if "if __name__" in chunk.content:
                    convention_files.add(file_path)
                    chunks = data.get("chunks", [])
                    entry_points.append({
                        "path": file_path,
                        "method": "detected entry point",
                        "chunk_names": [c.name for c in chunks if c.parent_id is None],
                    })
                    break

    # Fan-in analysis: files that are not imported by any other file
    # Build a set of files that ARE imported (have incoming import references)
    imported_files: set[str] = set()
    for file_path, data in file_data.items():
        chunks = data.get("chunks", [])
        chunk_ids = {c.id for c in chunks}
        for rel in data.get("relationships", []):
            source_id = rel.get("source_id", "")
            target_id = rel.get("target_id", "")
            if rel.get("rel_type") != "imports" or source_id not in chunk_ids:
                continue

            if source_id != target_id:
                # Resolved: target is in another file
                target_file = target_id.split("::")[0] if "::" in target_id else ""
                if target_file and target_file != file_path:
                    imported_files.add(target_file)
            else:
                # Unresolved: match by import name
                target_name = rel.get("target_name", "")
                if target_name:
                    last_part = target_name.split(".")[-1]
                    for other_fp, other_data in file_data.items():
                        if other_fp == file_path:
                            continue
                        if Path(other_fp).stem == last_part:
                            imported_files.add(other_fp)

    for file_path, data in file_data.items():
        if file_path in convention_files:
            continue

        relationships = data.get("relationships", [])
        chunks = data.get("chunks", [])
        has_outgoing = any(
            r.get("rel_type") in ("imports", "calls")
            and r.get("source_id", "") in {c.id for c in chunks}
            for r in relationships
        )

        if file_path not in imported_files and has_outgoing:
            chunks = data.get("chunks", [])
            entry_points.append({
                "path": file_path,
                "method": "likely entry point",
                "chunk_names": [c.name for c in chunks if c.parent_id is None],
            })

    return entry_points


def _compute_key_interfaces(file_data: dict[str, dict]) -> list[dict]:
    """Identify key interfaces by counting incoming relationships per chunk.

    Chunks with many incoming imports/calls from other files are key interfaces.

    Args:
        file_data: Dict of {path: {record, chunks, relationships, summary}}.

    Returns:
        List of dicts sorted by used_by_count descending, with keys:
        name, type, file, used_by_count, summary.
    """
    # Build a map of chunk_id → chunk info for resolving targets
    chunk_info: dict[str, dict] = {}
    for file_path, data in file_data.items():
        for chunk in data.get("chunks", []):
            chunk_info[chunk.id] = {
                "name": chunk.name,
                "type": chunk.chunk_type.value,
                "file": file_path,
                "summary": chunk.summary or "",
            }

    # Count incoming edges per chunk from other files
    # Use both resolved cross-file relationships and unresolved import names
    incoming_counts: dict[str, int] = {}  # chunk_id → count
    source_files: dict[str, set[str]] = {}  # chunk_id → set of source files

    # Build import-name → chunk_id map for unresolved imports
    import_to_chunk: dict[str, list[str]] = {}  # import_name → [chunk_ids]
    for cid, info in chunk_info.items():
        name = info.get("name", "")
        if name:
            import_to_chunk.setdefault(name, []).append(cid)

    for file_path, data in file_data.items():
        chunk_ids = {c.id for c in data.get("chunks", [])}
        for rel in data.get("relationships", []):
            if rel.get("rel_type") not in ("imports", "calls"):
                continue

            source_id = rel.get("source_id", "")
            target_id = rel.get("target_id", "")

            if source_id not in chunk_ids:
                continue

            if source_id != target_id:
                # Resolved cross-file relationship
                if target_id in chunk_info:
                    incoming_counts[target_id] = incoming_counts.get(target_id, 0) + 1
                    source_files.setdefault(target_id, set()).add(file_path)
            else:
                # Unresolved — use target_name to find matching chunks
                target_name = rel.get("target_name", "")
                if target_name:
                    # Try exact match on import name's last segment
                    last_part = target_name.split(".")[-1]
                    for matched_cid in import_to_chunk.get(last_part, []):
                        # Only count if the matched chunk is in a different file
                        if chunk_info[matched_cid].get("file", "") != file_path:
                            incoming_counts[matched_cid] = incoming_counts.get(matched_cid, 0) + 1
                            source_files.setdefault(matched_cid, set()).add(file_path)

    # Sort by count descending and take top 10
    sorted_ids = sorted(incoming_counts.keys(), key=lambda x: -incoming_counts.get(x, 0))[:10]

    result = []
    for cid in sorted_ids:
        info = chunk_info.get(cid, {})
        result.append({
            "name": info.get("name", "?"),
            "type": info.get("type", "?"),
            "file": info.get("file", "?"),
            "used_by_count": len(source_files.get(cid, set())),
            "summary": info.get("summary", ""),
        })

    return result


def generate_architecture_md(file_data: dict[str, dict]) -> str:
    """Generate ARCHITECTURE.md with module-level codebase overview.

    Produces a high-level view of the codebase organized by modules,
    including dependency graph, entry points, and key interfaces.
    All data is derived from the pre-assembled file_data dict — no
    new store queries are needed.

    Args:
        file_data: Dict of {path: {"record", "chunks", "relationships", "summary"}}.

    Returns:
        Complete ARCHITECTURE.md markdown string.
    """
    lines: list[str] = []

    # Header
    lines.append("# Architecture Overview")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).isoformat()}")

    # Module grouping
    modules = _group_by_module(file_data)
    lines.append(f"**Total Modules:** {len(modules)}")
    lines.append("")

    # ── Section 1: Project Structure Overview ──
    lines.append("## Project Structure Overview")
    lines.append("")

    for module_name, file_paths in modules.items():
        lines.append(f"### Module: {module_name}")
        lines.append("")
        lines.append("| File | Chunks | Summary |")
        lines.append("| ---- | ------ | ------- |")

        module_chunks: list[Chunk] = []
        for fp in file_paths:
            data = file_data[fp]
            chunks = data.get("chunks", [])
            module_chunks.extend(chunks)
            summary = data.get("summary", "")
            short_summary = summary[:80] + "..." if len(summary) > 80 else summary
            lines.append(f"| {fp} | {len(chunks)} | {short_summary} |")

        lines.append("")

        # Module narrative from chunk summaries
        narrative_parts: list[str] = []
        for chunk in module_chunks:
            if chunk.summary:
                narrative_parts.append(f"{chunk.name}: {chunk.summary}")

        if not narrative_parts:
            # Fallback: use rule-based summaries per file
            for fp in file_paths:
                data = file_data[fp]
                chunks = data.get("chunks", [])
                rels = data.get("relationships", [])
                rule = generate_rule_summary(fp, chunks, rels)
                narrative_parts.append(f"{Path(fp).stem}: {rule}")

        if narrative_parts:
            narrative = "; ".join(narrative_parts)
            if len(narrative) > 300:
                narrative = narrative[:297] + "..."
            lines.append(narrative)
            lines.append("")

    # ── Section 2: Module Dependency Graph ──
    lines.append("## Module Dependencies")
    lines.append("")

    # Compute module-level dependencies
    module_deps: dict[str, set[str]] = {}
    for file_path, data in file_data.items():
        my_module = _get_module_name(file_path)
        chunks = data.get("chunks", [])
        chunk_ids = {c.id for c in chunks}

        for rel in data.get("relationships", []):
            if rel.get("rel_type") not in ("imports", "calls"):
                continue

            source_id = rel.get("source_id", "")
            target_id = rel.get("target_id", "")

            # Only outgoing relationships from our files
            if source_id not in chunk_ids:
                continue

            target_module = None

            if source_id != target_id:
                # Resolved cross-file relationship
                target_file = target_id.split("::")[0] if "::" in target_id else ""
                if target_file and target_file != file_path and target_file in file_data:
                    target_module = _get_module_name(target_file)
            else:
                # Unresolved (self-referential) — use target_name to infer module
                target_name = rel.get("target_name", "")
                if target_name:
                    target_module = _module_from_import_name(target_name, file_data)

            if target_module and target_module != my_module:
                module_deps.setdefault(my_module, set()).add(target_module)

    # Render dependency table
    all_modules_with_deps = sorted(
        set(modules.keys()) | set(module_deps.keys()) | {d for deps in module_deps.values() for d in deps}
    )

    lines.append("| Module | Depends On |")
    lines.append("| ------ | ---------- |")
    for mod in all_modules_with_deps:
        deps = module_deps.get(mod, set())
        if deps:
            lines.append(f"| {mod} | {', '.join(sorted(deps))} |")
        else:
            lines.append(f"| {mod} | *(no external dependencies)* |")
    lines.append("")

    # ── Section 3: Entry Points ──
    lines.append("## Entry Points")
    lines.append("")

    entry_points = _detect_entry_points(file_data)
    if entry_points:
        lines.append("| File | Detection Method | Key Chunks |")
        lines.append("| ---- | ---------------- | ---------- |")
        for ep in entry_points:
            chunk_str = ", ".join(ep["chunk_names"][:5]) or "*(no top-level chunks)*"
            lines.append(f"| {ep['path']} | {ep['method']} | {chunk_str} |")
    else:
        lines.append("*(No entry points detected)*")
    lines.append("")

    # ── Section 4: Key Interfaces ──
    lines.append("## Key Interfaces")
    lines.append("")

    key_interfaces = _compute_key_interfaces(file_data)
    if key_interfaces:
        lines.append("| Name | Type | File | Used By (files) |")
        lines.append("| ---- | ---- | ---- | --------------- |")
        for iface in key_interfaces:
            name_str = iface["name"]
            if iface["summary"]:
                summary_short = iface["summary"][:40] + "..." if len(iface["summary"]) > 40 else iface["summary"]
                name_str = f"{name_str} ({summary_short})"
            lines.append(f"| {name_str} | {iface['type']} | {iface['file']} | {iface['used_by_count']} files |")
    else:
        lines.append("*(No key interfaces identified)*")
    lines.append("")

    return "\n".join(lines)


def export_index(
    repo_root: Path,
    config: ExportConfig,
    store: LadybugStore,
    console: Optional[object] = None,
) -> Path:
    """Export the full index as static markdown files.

    Supports three output modes:
    - Directory: --output ./dir
    - Archive: --output export.tar.gz
    - Stdout: --output -

    Args:
        repo_root: Absolute path to repository root.
        config: Export configuration.
        store: LadybugStore instance.
        console: Rich console for progress output.

    Returns:
        Path to the output (directory or archive file). For stdout mode, returns Path("-").
    """
    indexed_files = store.get_indexed_files()

    if console:
        console.print(f"[bold]glma[/bold] exporting [cyan]{len(indexed_files)}[/cyan] indexed files")

    # Load all file data from store
    file_data: dict[str, dict] = {}
    for file_path in sorted(indexed_files.keys()):
        record = store.get_file_record(file_path)
        chunks = store.get_chunks_for_file(file_path)
        relationships = store.get_file_relationships(file_path)

        # Use AI chunk summaries from DB if available, fall back to rule-based
        ai_summaries = [c.summary for c in chunks if c.summary]
        if ai_summaries:
            summary = "; ".join(ai_summaries)
        else:
            summary = generate_rule_summary(file_path, chunks, relationships)

        file_data[file_path] = {
            "record": record,
            "chunks": chunks,
            "relationships": relationships,
            "summary": summary,
        }

    # Generate per-file export markdown
    file_exports: dict[str, str] = {}
    for file_path, data in file_data.items():
        export_md = _format_export_file(
            file_path,
            data["record"],
            data["chunks"],
            data["relationships"],
            config,
            file_summary=data["summary"],
        )
        file_exports[file_path] = export_md

    # Generate root files
    index_md = generate_index_md(indexed_files, file_data)
    rels_md = generate_relationships_md(file_data)
    arch_md = generate_architecture_md(file_data)

    # Determine output mode
    output = config.output_path or "glma-export"

    if output == "-":
        # Stdout mode: stream tar to stdout
        _write_tar_to_stream(sys.stdout.buffer, file_exports, index_md, rels_md, arch_md)
        return Path("-")
    elif output.endswith(".tar.gz") or output.endswith(".tgz"):
        # Archive mode
        output_path = Path(output)
        with open(output_path, "wb") as f:
            _write_tar_to_stream(f, file_exports, index_md, rels_md, arch_md)
        if console:
            console.print(f"[green]✓[/green] Exported to {output_path}")
        return output_path
    else:
        # Directory mode
        output_dir = Path(output)
        output_dir.mkdir(parents=True, exist_ok=True)
        _write_files_to_dir(output_dir, file_exports, index_md, rels_md, arch_md)
        if console:
            console.print(f"[green]✓[/green] Exported to {output_dir}/")
        return output_dir


def _write_files_to_dir(
    output_dir: Path,
    file_exports: dict[str, str],
    index_md: str,
    rels_md: str,
    arch_md: str,
) -> None:
    """Write export files to a directory.

    Args:
        output_dir: Target directory.
        file_exports: Dict of {relative_path: markdown_content}.
        index_md: INDEX.md content.
        rels_md: RELATIONSHIPS.md content.
        arch_md: ARCHITECTURE.md content.
    """
    # Write per-file exports
    for file_path, content in file_exports.items():
        # Create nested mirror structure: export/src/auth/login.py.md
        md_path = output_dir / (file_path + ".md")
        md_path.parent.mkdir(parents=True, exist_ok=True)
        md_path.write_text(content, encoding="utf-8")

    # Write INDEX.md
    (output_dir / "INDEX.md").write_text(index_md, encoding="utf-8")

    # Write RELATIONSHIPS.md
    (output_dir / "RELATIONSHIPS.md").write_text(rels_md, encoding="utf-8")

    # Write ARCHITECTURE.md
    (output_dir / "ARCHITECTURE.md").write_text(arch_md, encoding="utf-8")


def _write_tar_to_stream(
    stream: io.RawIOBase,
    file_exports: dict[str, str],
    index_md: str,
    rels_md: str,
    arch_md: str,
) -> None:
    """Write export as tar.gz archive to a stream.

    Args:
        stream: Writable binary stream (file or stdout.buffer).
        file_exports: Dict of {relative_path: markdown_content}.
        index_md: INDEX.md content.
        rels_md: RELATIONSHIPS.md content.
        arch_md: ARCHITECTURE.md content.
    """
    with tarfile.open(fileobj=stream, mode="w|gz") as tar:
        # Add per-file exports
        for file_path, content in file_exports.items():
            data = content.encode("utf-8")
            info = tarfile.TarInfo(name=file_path + ".md")
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))

        # Add INDEX.md
        data = index_md.encode("utf-8")
        info = tarfile.TarInfo(name="INDEX.md")
        info.size = len(data)
        tar.addfile(info, io.BytesIO(data))

        # Add RELATIONSHIPS.md
        data = rels_md.encode("utf-8")
        info = tarfile.TarInfo(name="RELATIONSHIPS.md")
        info.size = len(data)
        tar.addfile(info, io.BytesIO(data))

        # Add ARCHITECTURE.md
        data = arch_md.encode("utf-8")
        info = tarfile.TarInfo(name="ARCHITECTURE.md")
        info.size = len(data)
        tar.addfile(info, io.BytesIO(data))
